apiVersion: v1
kind: Service
metadata:
  name: stealth-memory-leaker-service
  namespace: memleak-demo
  labels:
    app: stealth-memory-leaker
    purpose: "stealth-memory-leak-demo"
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
    # HTTP 서비스 (헬스체크용)
  - port: 9090
    targetPort: 9090
    protocol: TCP
    name: metrics
    # Prometheus 메트릭용
  selector:
    app: stealth-memory-leaker
---
apiVersion: v1
kind: Service
metadata:
  name: stealth-memory-leaker-headless
  namespace: memleak-demo
  labels:
    app: stealth-memory-leaker
    purpose: "stealth-memory-leak-demo"
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  - port: 9090
    targetPort: 9090
    protocol: TCP
    name: metrics
  selector:
    app: stealth-memory-leaker