apiVersion: v1
kind: Service
metadata:
  name: memory-leaker-service
  namespace: memleak-demo
  labels:
    app: memory-leaker
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: memory-leaker
---
apiVersion: v1
kind: Service
metadata:
  name: memory-leaker-headless
  namespace: memleak-demo
  labels:
    app: memory-leaker
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: memory-leaker