apiVersion: v1
kind: Service
metadata:
  name: leaky-service
  namespace: memleak-demo
  labels:
    app: leaky
spec:
  type: ClusterIP
  ports:
  - port: 6060
    targetPort: 6060
    protocol: TCP
    name: pprof
  selector:
    app: leaky